version: "3.9"

services:
  app:
    image: markoshust/magento-nginx:1.24-0
    expose:
      - "80"
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:cached
      - ~/.ssh/id_rsa:/var/www/.ssh/id_rsa:cached
      - ~/.ssh/known_hosts:/var/www/.ssh/known_hosts:cached
      - appdata:/var/www/html
      - sockdata:/sock
      - ssldata:/etc/nginx/certs

  phpfpm:
    image: markoshust/magento-php:8.3-fpm-4
    volumes: *appvolumes
    env_file: env/phpfpm.env

  db:
    image: mariadb:11.4
    command:
      --max_allowed_packet=64M
      --optimizer_use_condition_selectivity=1
      --optimizer_switch="rowid_filter=off"
      --log_bin_trust_function_creators=1
    environment:
      MARIADB_ROOT_PASSWORD: rootpwd-change-me
      MARIADB_DATABASE: magento
      MARIADB_USER: magento
      MARIADB_PASSWORD: magento
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: valkey/valkey:8.1-alpine

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    expose:
      - "9200"

  rabbitmq:
    image: markoshust/magento-rabbitmq:4.1-0
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    env_file: env/rabbitmq.env

  mailcatcher:
    image: sj26/mailcatcher:v0.10.0
    expose:
      - "1080"

volumes:
  appdata:
  dbdata:
  rabbitmqdata:
  sockdata:
  ssldata:
  esdata:
